security:
    role_hierarchy:
        ROLE_SELLER:      ROLE_USER
        ROLE_ADMIN:       ROLE_SELLER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        notifyPage:
            pattern: ^/api/notify-page
            stateless: true
            anonymous: true

        redirectPage:
            pattern: ^/api/redirect-page
            stateless: true
            anonymous: true

        payment:
            pattern: ^/api/done
            stateless: true
            anonymous: true

        register:
            pattern: ^/api/register
            stateless: true
            anonymous: true

        mixed:
            pattern: ^/api/cart
            stateless: true
            anonymous: true
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator
            json_login:
                check_path:               /api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        admin:
            pattern: ^/admin
            provider: our_db_provider
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
                default_target_path: /admin/dashboard
            logout:
                path:   /admin/logout
                target: /

            # activate different ways to authenticate

#            http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        #payment
        - { path: ^/api/done,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/redirect-page, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/notify-page,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #mixed(cart)
        - { path: ^/api/cart,          roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #api
        - { path: ^/api/login,         roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register,      roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,               roles: IS_AUTHENTICATED_FULLY }
        #admin
        - { path: ^/admin/login,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,             roles: ROLE_ADMIN}
